### ISSUE TITLE
버그바운티를 위한 1차 배포

### ISSUE THREAD

**Issue by kimgunwooo** [kimgunwooo/FQS-Flexible-Queue-Service#44]
## 💡 Feature Issue
버그바운티를 위한 1차 배포를 진행합니다.

## 🌿  To-do

- [ ] ~~EKS를 통한 k8s 클러스터 구축~~
- [ ] ~~Mysql-RDS, redis,kafka 는 helm 을 통한 클러스터 내 구축~~
- [ ] ~~ECR을 통한 private registry 사용~~
- [ ] 배포하기..
