### ISSUE TITLE
Kafka application setting

### ISSUE THREAD

**Issue by J0minsu** [kimgunwooo/FQS-Flexible-Queue-Service#6]
## 💡 Feature Issue

Kafka 를 사용하기 위한 의존성 추가 및 기초가 되는 producer, consumer 설정

## 🌿  To-do

- [x] kafka 관련 의존성 추가 및 정상 작통 확인
- [x] kafka 대기열 전용 producer/consumer 작성(prototype)
- [x] kafka Event Sourcing 전용 producer/consumer 작성
