### ISSUE TITLE
사용 설명서 적기

### ISSUE THREAD

**Issue by J0minsu** [kimgunwooo/FQS-Flexible-Queue-Service#64]
## 💡 Feature Issue
FQS 사용 설명서 작성

## 🌿  To-do

- [ ] 로그인 프로세스 설명
- [ ] 대기열 생성 프로세스 설명
- [ ] 대기열 종료 프로세스 설명
