### ISSUE TITLE
Queue Server 기초 세팅

### ISSUE THREAD

**Issue by kimgunwooo** [kimgunwooo/FQS-Flexible-Queue-Service#7]
## 💡 Feature Issue
Queue Server의 데이터베이스 스키마를 정의하고, 간단 API 개발 및 목업 데이터 생성

## 🌿  To-do

- [ ] Queue Server DB Modeling
- [ ] 대기열 생성 API (개발)
- [ ] 그 외 API Mock up (가라데이터 API 스펙 정의)
